(()=>{'use strict';
const {Engine,World,Bodies,Body,Events}=Matter;
const VERSION='Beta 0.0.1';
const GAME_ID='frutas';
const TIERS=[
{id:'roxa',name:'Roxa',emoji:'🍇',color:'#6f4ba8',r:17,score:0,density:.0011},
{id:'vermelha',name:'Vermelha',emoji:'🍒',color:'#d84f55',r:22,score:10,density:.0013},
{id:'verde',name:'Verde',emoji:'🍏',color:'#8dbf57',r:28,score:25,density:.0016},
{id:'banana',name:'Banana',emoji:'🍌',color:'#efc84c',r:34,score:60,density:.0019},
{id:'laranja',name:'Laranja',emoji:'🍊',color:'#ee933f',r:40,score:120,density:.0023},
{id:'maca',name:'Maçã',emoji:'🍎',color:'#d65e4c',r:47,score:220,density:.0027},
{id:'pessego',name:'Pêssego',emoji:'🍑',color:'#ef9b88',r:55,score:360,density:.0032},
{id:'melao',name:'Melão',emoji:'🍈',color:'#b9cf75',r:64,score:550,density:.0038},
{id:'melancia',name:'Melancia',emoji:'🍉',color:'#5a9b4e',r:75,score:800,density:.0045},
{id:'abacaxi',name:'Abacaxi',emoji:'🍍',color:'#d7a83f',r:86,score:1200,density:.0053}
];
const SPAWN_POOL=[0,0,0,1,1,1,2,2,3,4];
const $=id=>document.getElementById(id),canvas=$('gameCanvas'),ctx=canvas.getContext('2d'),wrap=canvas.parentElement;
const engine=Engine.create({enableSleeping:true});engine.gravity.y=1.02;
let walls=[],fruits=[],merging=new Set(),score=0,nextTier=randomSpawn(),dropTier=nextTier,dropX=160,canDrop=true,gameOver=false,paused=false,dangerSince=0,session=null,panelRules=[];
let width=360,height=560,last=performance.now();
const manifest={protocol:'liveplus-game-manifest-v1',gameId:GAME_ID,name:'Frutas · Merge Live',icon:'🍉',version:VERSION,actions:[
{id:'drop_fruit',label:'Soltar fruta',icon:'🍇',description:'Solta uma fruta pelo painel.',params:[{id:'tier',label:'FRUTA',type:'select',default:'random',options:[{value:'random',label:'Aleatória'},...TIERS.slice(0,7).map((t,i)=>({value:String(i),label:`${t.emoji} ${t.name}`}))]}]},
{id:'set_next_fruit',label:'Definir próxima fruta',icon:'🎯',description:'Escolhe a próxima fruta da fila.',params:[{id:'tier',label:'FRUTA',type:'select',default:'0',options:TIERS.slice(0,7).map((t,i)=>({value:String(i),label:`${t.emoji} ${t.name}`}))}]},
{id:'add_score',label:'Adicionar pontos',icon:'➕',description:'Soma pontos ao placar.',params:[{id:'amount',label:'PONTOS',type:'number',min:1,max:100000,default:100}]},
{id:'set_score',label:'Definir pontos',icon:'🏆',description:'Define o placar total.',params:[{id:'amount',label:'TOTAL',type:'number',min:0,max:999999999,default:0}]},
{id:'shake',label:'Balançar caixa',icon:'🫨',description:'Aplica um pequeno impulso às frutas.',params:[{id:'power',label:'FORÇA',type:'number',min:1,max:10,default:4}]},
{id:'clear_small',label:'Limpar frutas pequenas',icon:'🧹',description:'Remove frutas até um nível escolhido.',params:[{id:'maxTier',label:'ATÉ O NÍVEL',type:'number',min:0,max:4,default:1}]},
{id:'pause_game',label:'Pausar/continuar',icon:'⏯️',description:'Alterna a pausa da partida.',params:[]},
{id:'reset_game',label:'Reiniciar partida',icon:'♻️',description:'Zera a pontuação e limpa a caixa.',params:[]}
]};
function randomSpawn(){return SPAWN_POOL[(Math.random()*SPAWN_POOL.length)|0]}function clamp(v,min,max){return Math.max(min,Math.min(max,v))}
function resize(){const rect=wrap.getBoundingClientRect(),dpr=Math.min(2,window.devicePixelRatio||1);width=Math.max(280,Math.round(rect.width));height=Math.max(360,Math.round(rect.height));canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);canvas.style.width=width+'px';canvas.style.height=height+'px';ctx.setTransform(dpr,0,0,dpr,0,0);rebuildWalls();dropX=clamp(dropX,30,width-30);updateAim()}
function rebuildWalls(){walls.forEach(w=>World.remove(engine.world,w));const thick=50;walls=[Bodies.rectangle(-thick/2,height/2,thick,height*2,{isStatic:true,label:'wall'}),Bodies.rectangle(width+thick/2,height/2,thick,height*2,{isStatic:true,label:'wall'}),Bodies.rectangle(width/2,height+thick/2,width+thick*2,thick,{isStatic:true,label:'floor'})];World.add(engine.world,walls)}
function makeFruit(tier,x,y,opts={}){tier=clamp(Number(tier)||0,0,TIERS.length-1);const t=TIERS[tier],body=Bodies.circle(clamp(x,t.r,width-t.r),y,t.r,{label:'fruit',restitution:.08,friction:.18,frictionStatic:.5,frictionAir:.006,density:t.density,slop:.02});body.fruitTier=tier;body.spawnedAt=Date.now();body.mergeLock=false;if(opts.vx||opts.vy)Body.setVelocity(body,{x:opts.vx||0,y:opts.vy||0});fruits.push(body);World.add(engine.world,body);return body}
function removeFruit(body){const i=fruits.indexOf(body);if(i>=0)fruits.splice(i,1);World.remove(engine.world,body);merging.delete(body.id)}
function mergePair(a,b){if(!a||!b||a.mergeLock||b.mergeLock||a.fruitTier!==b.fruitTier||a.fruitTier>=TIERS.length-1)return;a.mergeLock=b.mergeLock=true;merging.add(a.id);merging.add(b.id);const next=a.fruitTier+1,x=(a.position.x+b.position.x)/2,y=(a.position.y+b.position.y)/2,vx=(a.velocity.x+b.velocity.x)*.22,vy=(a.velocity.y+b.velocity.y)*.12;setTimeout(()=>{if(!fruits.includes(a)||!fruits.includes(b))return;removeFruit(a);removeFruit(b);const c=makeFruit(next,x,y,{vx,vy});Body.setAngularVelocity(c,(a.angularVelocity+b.angularVelocity)*.2);addScore(TIERS[next].score,'merge');pulseScore();sendEvent('fruit_merged',{fromTier:next-1,toTier:next,points:TIERS[next].score});sendState('merge')},0)}
Events.on(engine,'collisionStart',ev=>{for(const pair of ev.pairs){const a=pair.bodyA,b=pair.bodyB;if(a.label==='fruit'&&b.label==='fruit'&&a.fruitTier===b.fruitTier)mergePair(a,b)}});
function addScore(n,reason='manual'){score=Math.max(0,Math.round(score+(Number(n)||0)));$('score').textContent=score.toLocaleString('pt-BR');if(reason!=='merge')sendState('score')}function pulseScore(){const el=$('score');el.animate?.([{transform:'scale(1)'},{transform:'scale(1.18)'},{transform:'scale(1)'}],{duration:240})}
function updateNextUI(){const t=TIERS[nextTier];$('nextFruit').textContent=t.emoji;dropTier=nextTier;$('dropPreview').textContent=t.emoji;updateAim()}function updateAim(){const r=TIERS[dropTier].r;dropX=clamp(dropX,r+3,width-r-3);$('aimLine').style.left=dropX+'px';$('dropPreview').style.left=dropX+'px';$('dropPreview').style.fontSize=Math.min(48,Math.max(28,r*1.15))+'px'}
function drop(tier=null,x=dropX,source='player'){if(gameOver||paused||!canDrop)return false;const chosen=tier===null?dropTier:clamp(Number(tier)||0,0,TIERS.length-1),t=TIERS[chosen];makeFruit(chosen,clamp(x,t.r+3,width-t.r-3),Math.max(18,t.r+4));canDrop=false;setTimeout(()=>{canDrop=true},330);if(tier===null){nextTier=randomSpawn();updateNextUI()}sendEvent('fruit_dropped',{tier:chosen,source});sendState('drop');return true}
function resetGame(){fruits.slice().forEach(removeFruit);score=0;$('score').textContent='0';nextTier=randomSpawn();updateNextUI();gameOver=false;paused=false;dangerSince=0;hideMessage();sendEvent('game_reset');sendState('reset')}function showMessage(html){const el=$('gameMessage');el.innerHTML=html;el.hidden=false}function hideMessage(){$('gameMessage').hidden=true}function endGame(){if(gameOver)return;gameOver=true;showMessage(`FIM DE JOGO<br><small>${score.toLocaleString('pt-BR')} pontos</small>`);sendEvent('game_over',{score});sendState('gameover')}
function checkDanger(){if(gameOver||paused)return;const now=Date.now(),risky=fruits.some(b=>now-b.spawnedAt>1300&&b.position.y-TIERS[b.fruitTier].r<88&&Math.hypot(b.velocity.x,b.velocity.y)<1.1);if(risky){if(!dangerSince)dangerSince=now;if(now-dangerSince>2300)endGame()}else dangerSince=0}
function shade(hex,amt){const n=parseInt(hex.slice(1),16),r=clamp((n>>16)+amt,0,255),g=clamp(((n>>8)&255)+amt,0,255),b=clamp((n&255)+amt,0,255);return'#'+((1<<24)+(r<<16)+(g<<8)+b).toString(16).slice(1)}
function drawFruit(b){const t=TIERS[b.fruitTier],x=b.position.x,y=b.position.y,r=t.r;ctx.save();ctx.translate(x,y);ctx.rotate(b.angle);const g=ctx.createRadialGradient(-r*.28,-r*.34,r*.05,0,0,r);g.addColorStop(0,'#fff7');g.addColorStop(.18,t.color);g.addColorStop(1,shade(t.color,-28));ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.fill();ctx.lineWidth=Math.max(1.5,r*.045);ctx.strokeStyle='#654334aa';ctx.stroke();ctx.rotate(-b.angle);ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`${Math.max(18,r*1.08)}px Apple Color Emoji,Segoe UI Emoji,sans-serif`;ctx.fillText(t.emoji,0,1);ctx.restore()}
function draw(){ctx.clearRect(0,0,width,height);for(const b of fruits)drawFruit(b)}function tick(now){const dt=Math.min(33,Math.max(8,now-last));last=now;if(!paused&&!gameOver)Engine.update(engine,dt);checkDanger();draw();requestAnimationFrame(tick)}
function stateSnapshot(scope='game'){return{scope,gameId:GAME_ID,version:VERSION,score,gameOver,paused,nextTier,nextFruit:TIERS[nextTier].id,fruitCount:fruits.length,highestTier:fruits.reduce((m,b)=>Math.max(m,b.fruitTier),0),rules:panelRules.length,transport:session?.getTransport?.()||'offline'}}function sendState(scope='game'){session?.sendState(stateSnapshot(scope))}function sendEvent(event,data={}){session?.sendEvent({gameId:GAME_ID,event,...data})}
function executeCommand(data={}){if(data.gameId&&String(data.gameId)!==GAME_ID)return false;const action=String(data.action||data.command||''),p=data.params&&typeof data.params==='object'?data.params:{};switch(action){case'drop_fruit':{const tier=p.tier==='random'?randomSpawn():clamp(Number(p.tier)||0,0,TIERS.length-1);return drop(tier,dropX,'panel')}case'set_next_fruit':nextTier=clamp(Number(p.tier)||0,0,TIERS.length-1);updateNextUI();sendState('next');return true;case'add_score':addScore(Math.max(0,Number(p.amount)||0));return true;case'set_score':score=Math.max(0,Math.round(Number(p.amount)||0));$('score').textContent=score.toLocaleString('pt-BR');sendState('score');return true;case'shake':{const power=clamp(Number(p.power)||4,1,10);fruits.forEach(b=>Body.applyForce(b,b.position,{x:(Math.random()-.5)*.0008*power*b.mass,y:-.00012*power*b.mass}));sendEvent('box_shaken',{power});return true}case'clear_small':{const max=clamp(Number(p.maxTier)||0,0,4);fruits.slice().filter(b=>b.fruitTier<=max).forEach(removeFruit);sendState('clear');return true}case'pause_game':paused=!paused;if(paused)showMessage('PAUSADO');else hideMessage();sendState('pause');return true;case'reset_game':resetGame();return true;default:return false}}
function setPairStatus(text,kind=''){const e=$('pairMessage');e.textContent=text;e.className='pair-message '+kind;$('panelStatus').textContent=text;$('statusDot').className=kind}function cleanCode(v=''){return String(v).toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,8)}function formatCode(v=''){const c=cleanCode(v);return c.length>4?c.slice(0,4)+'-'+c.slice(4):c}
async function connectPanel(){const input=$('panelCode'),code=cleanCode(input.value);input.value=formatCode(code);if(code.length!==8){setPairStatus('Código inválido','err');return}if(!window.LivePlusGameSDK?.Session){setPairStatus('SDK LIVE+ não carregou','err');return}session?.disconnect?.();session=new window.LivePlusGameSDK.Session({storageKey:'frutas-liveplus-token',manifest});session.addEventListener('connected',()=>{setPairStatus('Painel conectado','ok');sendState('initial');setTimeout(()=>$('panelModal').classList.remove('show'),300)});session.addEventListener('command',e=>{const ok=executeCommand(e.detail||{});session?.sendState({scope:'command',gameId:GAME_ID,commandStatus:ok?'executed':'unsupported',action:String(e.detail?.action||'')})});session.addEventListener('message',e=>{const d=e.detail||{};if(d.type==='rules_sync'&&Array.isArray(d.rules)){panelRules=d.rules;sendState('rules')}});session.addEventListener('reconnecting',()=>setPairStatus('Reconectando…','warn'));session.addEventListener('lost',()=>setPairStatus('Conexão perdida','err'));session.addEventListener('rejected',e=>setPairStatus(e.detail?.reason||'Sessão recusada','err'));setPairStatus('Conectando…','warn');try{localStorage.setItem('frutas-panel-code',formatCode(code))}catch{}try{await session.connect(code)}catch(err){setPairStatus(err?.message||'Falha ao conectar','err')}}
function pointerX(e){const r=canvas.getBoundingClientRect();return clamp((e.clientX-r.left)*(width/r.width),20,width-20)}canvas.addEventListener('pointermove',e=>{dropX=pointerX(e);updateAim()});canvas.addEventListener('pointerup',e=>{dropX=pointerX(e);updateAim();drop()});addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){dropX-=18;updateAim()}else if(e.key==='ArrowRight'){dropX+=18;updateAim()}else if(e.code==='Space'){e.preventDefault();drop()}});
$('panelButton').onclick=()=>{$('panelModal').classList.add('show');$('panelModal').setAttribute('aria-hidden','false')};$('closePanel').onclick=()=>$('panelModal').classList.remove('show');$('panelModal').onclick=e=>{if(e.target===$('panelModal'))$('panelModal').classList.remove('show')};$('connectPanel').onclick=connectPanel;$('restartButton').onclick=resetGame;$('panelCode').oninput=e=>e.target.value=formatCode(e.target.value);$('panelCode').onkeydown=e=>{if(e.key==='Enter')connectPanel()};function buildProgression(){$('progressionTrack').innerHTML=TIERS.map((t,i)=>`<div class="tier-pill" title="${t.name}: ${t.score} pontos"><span>${t.emoji}</span><b>${i?`+${t.score}`:'INÍCIO'}</b></div>`).join('')}
try{const saved=localStorage.getItem('frutas-panel-code');if(saved)$('panelCode').value=saved}catch{}buildProgression();updateNextUI();resize();addEventListener('resize',resize);requestAnimationFrame(tick);window.FrutasGame={version:VERSION,gameId:GAME_ID,manifest,tiers:TIERS.map(t=>({...t})),executeCommand,dropFruit:(tier,x)=>drop(tier,x??dropX,'api'),setDropX:x=>{dropX=Number(x)||dropX;updateAim()},reset:resetGame,getState:stateSnapshot,connectPanel};
})();
