(()=>{'use strict';
const {Engine,World,Bodies,Body,Events}=Matter;
const C=window.FRUTAS_CONFIG||{};
const VERSION=C.version||'Beta 0.0.8';
const GAME_ID=C.gameId||'frutas';
const STORAGE_KEY=C.gameStorageKey||'frutas-game-state-v1';
const FIXED_STEP=1000/60;
const MAX_SUBSTEPS=2;
const DANGER_Y=84;
const DANGER_HOLD_MS=5000;
const BACKGROUND_RESUME_MS=1200;
const FINAL_MERGE_BONUS=Number(C.finalMergeBonus)||500;
const TIERS=[
{id:'roxa',name:'Roxa',color:'#6f4ba8',r:17,score:0,density:.0011},
{id:'vermelha',name:'Vermelha',color:'#d84f55',r:22,score:2,density:.0013},
{id:'verde',name:'Verde',color:'#8dbf57',r:28,score:4,density:.0016},
{id:'banana',name:'Amarela',color:'#efc84c',r:34,score:8,density:.0019},
{id:'laranja',name:'Laranja',color:'#ee933f',r:40,score:16,density:.0023},
{id:'maca',name:'Vermelha II',color:'#c94f42',r:47,score:30,density:.0027},
{id:'pessego',name:'Rosa',color:'#ef9b88',r:55,score:50,density:.0032},
{id:'melao',name:'Verde II',color:'#b9cf75',r:64,score:80,density:.0038},
{id:'melancia',name:'Verde III',color:'#5a9b4e',r:75,score:120,density:.0045},
{id:'abacaxi',name:'Dourada',color:'#d7a83f',r:86,score:180,density:.0053}
];
const SPAWN_POOL=[0,0,0,1,1,1,2,2,3,4];
const $=id=>document.getElementById(id),canvas=$('gameCanvas'),ctx=canvas.getContext('2d',{alpha:true}),wrap=canvas.parentElement;
const engine=Engine.create({enableSleeping:false});engine.gravity.y=1.08;engine.positionIterations=7;engine.velocityIterations=6;engine.constraintIterations=1;
let walls=[],fruits=[],merging=new Set(),score=0,dropTier=randomSpawn(),nextTier=randomSpawn(),dropX=160,canDrop=true,gameOver=false,paused=false,dangerSince=0,dangerBodyId=null;
let width=360,height=560,last=performance.now(),accumulator=0,lastDangerCheck=0,currentDpr=1,saveTimer=0,restoring=false;
let backgroundProtected=false,backgroundDangerRemaining=0,backgroundResumeTimer=0;
const fruitSprites=[];
function randomSpawn(){return SPAWN_POOL[(Math.random()*SPAWN_POOL.length)|0]}
function clamp(v,min,max){return Math.max(min,Math.min(max,v))}
function shade(hex,amt){const n=parseInt(hex.slice(1),16),r=clamp((n>>16)+amt,0,255),g=clamp(((n>>8)&255)+amt,0,255),b=clamp((n&255)+amt,0,255);return'#'+((1<<24)+(r<<16)+(g<<8)+b).toString(16).slice(1)}
function makeSprite(t){const pad=Math.max(4,Math.ceil(t.r*.08)),size=(t.r+pad)*2,c=document.createElement('canvas'),g=c.getContext('2d');c.width=size;c.height=size;const cx=size/2,cy=size/2,r=t.r,grad=g.createRadialGradient(cx-r*.3,cy-r*.34,Math.max(1,r*.04),cx,cy,r);grad.addColorStop(0,'rgba(255,255,255,.82)');grad.addColorStop(.18,t.color);grad.addColorStop(1,shade(t.color,-30));g.fillStyle=grad;g.beginPath();g.arc(cx,cy,r,0,Math.PI*2);g.fill();g.lineWidth=Math.max(1.4,r*.045);g.strokeStyle='rgba(85,55,43,.68)';g.stroke();g.beginPath();g.arc(cx-r*.27,cy-r*.31,Math.max(1.7,r*.13),0,Math.PI*2);g.fillStyle='rgba(255,255,255,.38)';g.fill();return c}
function rebuildSprites(){fruitSprites.length=0;for(const t of TIERS)fruitSprites.push(makeSprite(t))}
function setChip(el,tier){if(!el)return;const t=TIERS[tier];el.textContent='';el.style.setProperty('--fruit-color',t.color);el.style.setProperty('--fruit-dark',shade(t.color,-30));el.setAttribute('aria-label',t.name)}
function bodyRadius(body){const base=TIERS[body?.fruitTier]?.r||16;return base*(Number(body?.__liveScale)||1)}
function clampFruitToField(body,hard=false){if(!body||body.label!=='fruit')return;const r=bodyRadius(body);let x=body.position.x,y=body.position.y,changed=false;if(x<r){x=r;changed=true}else if(x>width-r){x=width-r;changed=true}if(y>height-r){y=height-r;changed=true}if(changed){Body.setPosition(body,{x,y});if(hard)Body.setVelocity(body,{x:clamp(body.velocity.x,-2.5,2.5),y:Math.min(0,body.velocity.y)*.12});else Body.setVelocity(body,{x:body.position.x<=r?Math.abs(body.velocity.x)*.12:body.position.x>=width-r?-Math.abs(body.velocity.x)*.12:body.velocity.x,y:y>=height-r?-Math.abs(body.velocity.y)*.06:body.velocity.y})}}
function enforcePlayfield(){for(const b of fruits){const r=bodyRadius(b);if(b.position.x<r-2||b.position.x>width-r+2||b.position.y>height-r+3)clampFruitToField(b,true)}}
function resize(){const mobile=matchMedia('(pointer:coarse)').matches;currentDpr=Math.min(mobile?1.35:1.6,window.devicePixelRatio||1);const nextWidth=Math.max(280,Math.round(wrap.clientWidth)),nextHeight=Math.max(220,Math.round(wrap.clientHeight));if(nextWidth===width&&nextHeight===height&&canvas.width)return;const oldW=width,oldH=height;width=nextWidth;height=nextHeight;canvas.style.width='100%';canvas.style.height='100%';canvas.width=Math.max(1,Math.round(width*currentDpr));canvas.height=Math.max(1,Math.round(height*currentDpr));ctx.setTransform(currentDpr,0,0,currentDpr,0,0);rebuildWalls();if(oldW>0&&oldH>0){const sx=width/oldW,sy=height/oldH;for(const b of fruits){Body.setPosition(b,{x:b.position.x*sx,y:b.position.y*sy});clampFruitToField(b,true)}}dropX=clamp(dropX,30,width-30);updateAim()}
function rebuildWalls(){walls.forEach(w=>World.remove(engine.world,w));const thick=140,sideHeight=height+thick*2;walls=[Bodies.rectangle(-thick/2,height/2,thick,sideHeight,{isStatic:true,label:'wall-left',friction:.001,frictionStatic:0,restitution:.01}),Bodies.rectangle(width+thick/2,height/2,thick,sideHeight,{isStatic:true,label:'wall-right',friction:.001,frictionStatic:0,restitution:.01}),Bodies.rectangle(width/2,height+thick/2,width+thick*2,thick,{isStatic:true,label:'floor',friction:.22,frictionStatic:.35,restitution:.01})];World.add(engine.world,walls)}
function makeFruit(tier,x,y,opts={}){tier=clamp(Number(tier)||0,0,TIERS.length-1);const t=TIERS[tier],body=Bodies.circle(clamp(x,t.r,width-t.r),y,t.r,{label:'fruit',restitution:.045,friction:.08,frictionStatic:.18,frictionAir:.002,density:t.density,slop:.012,sleepThreshold:Infinity});body.fruitTier=tier;body.spawnedAt=Number(opts.spawnedAt)||Date.now();body.mergeLock=false;body.__liveScale=1;if(opts.scale&&Number(opts.scale)!==1){Body.scale(body,Number(opts.scale),Number(opts.scale));body.__liveScale=Number(opts.scale)}if(Number.isFinite(opts.angle))Body.setAngle(body,opts.angle);if(opts.vx||opts.vy)Body.setVelocity(body,{x:opts.vx||0,y:opts.vy||0});if(Number.isFinite(opts.angularVelocity))Body.setAngularVelocity(body,opts.angularVelocity);fruits.push(body);World.add(engine.world,body);return body}
function removeFruit(body){const i=fruits.indexOf(body);if(i>=0)fruits.splice(i,1);World.remove(engine.world,body);merging.delete(body.id);if(body?.id===dangerBodyId)resetDanger();queueSave()}
function mergePair(a,b){if(!a||!b||a.mergeLock||b.mergeLock||a.fruitTier!==b.fruitTier)return;const tier=a.fruitTier;a.mergeLock=b.mergeLock=true;merging.add(a.id);merging.add(b.id);if(tier>=TIERS.length-1){queueMicrotask(()=>{if(!fruits.includes(a)||!fruits.includes(b))return;removeFruit(a);removeFruit(b);addScore(FINAL_MERGE_BONUS,'merge');pulseScore();sendEvent('fruit_merged',{fromTier:tier,toTier:null,points:FINAL_MERGE_BONUS,final:true});sendState('merge');queueSave()});return}const next=tier+1,x=clamp((a.position.x+b.position.x)/2,TIERS[next].r,width-TIERS[next].r),y=Math.min((a.position.y+b.position.y)/2,height-TIERS[next].r),vx=(a.velocity.x+b.velocity.x)*.22,vy=(a.velocity.y+b.velocity.y)*.12;queueMicrotask(()=>{if(!fruits.includes(a)||!fruits.includes(b))return;removeFruit(a);removeFruit(b);const c=makeFruit(next,x,y,{vx,vy});Body.setAngularVelocity(c,(a.angularVelocity+b.angularVelocity)*.2);clampFruitToField(c,true);addScore(TIERS[next].score,'merge');pulseScore();sendEvent('fruit_merged',{fromTier:next-1,toTier:next,points:TIERS[next].score});sendState('merge');queueSave()})}
Events.on(engine,'collisionStart',ev=>{for(const pair of ev.pairs){const a=pair.bodyA,b=pair.bodyB;if(a.label==='fruit'&&b.label==='fruit'&&a.fruitTier===b.fruitTier)mergePair(a,b)}});
function addScore(n,reason='manual'){score=Math.max(0,Math.round(score+(Number(n)||0)));$('score').textContent=score.toLocaleString('pt-BR');if(reason!=='merge')sendState('score');queueSave()}
function pulseScore(){const el=$('score');el.animate?.([{transform:'scale(1)'},{transform:'scale(1.12)'},{transform:'scale(1)'}],{duration:180})}
function updateNextUI(){setChip($('nextFruit'),nextTier);setChip($('dropPreview'),dropTier);updateAim()}
function updateAim(){const t=TIERS[dropTier],r=t.r;dropX=clamp(dropX,r+3,width-r-3);$('aimLine').style.left=dropX+'px';const preview=$('dropPreview');preview.style.left=dropX+'px';preview.style.width=(r*2)+'px';preview.style.height=(r*2)+'px'}
function drop(tier=null,x=dropX,source='player'){if(gameOver||paused||backgroundProtected||!canDrop)return false;const isPlayer=tier===null,chosen=isPlayer?dropTier:clamp(Number(tier)||0,0,TIERS.length-1),t=TIERS[chosen],body=makeFruit(chosen,clamp(x,t.r+3,width-t.r-3),Math.max(18,t.r+4));canDrop=false;setTimeout(()=>{canDrop=true},300);if(isPlayer){dropTier=nextTier;nextTier=randomSpawn();updateNextUI()}sendEvent('fruit_dropped',{tier:chosen,source});sendState('drop');queueSave();return body}
function ensureDangerHud(){let el=$('dangerCountdown');if(el)return el;el=document.createElement('div');el.id='dangerCountdown';el.className='danger-countdown';el.hidden=true;wrap.appendChild(el);return el}
function resetDanger(){dangerSince=0;dangerBodyId=null;backgroundDangerRemaining=0;const el=ensureDangerHud();el.hidden=true;el.textContent=''}
function dangerRemaining(){if(backgroundProtected)return Math.max(0,backgroundDangerRemaining);return dangerSince?Math.max(0,DANGER_HOLD_MS-(Date.now()-dangerSince)):0}
function updateDangerHud(remaining){const el=ensureDangerHud();el.hidden=false;el.textContent='PERIGO · '+Math.max(1,Math.ceil(remaining/1000))+'s'}
function clearSavedGame(){try{localStorage.removeItem(STORAGE_KEY)}catch{}}
function resetGame(){clearTimeout(backgroundResumeTimer);backgroundProtected=false;backgroundDangerRemaining=0;fruits.slice().forEach(removeFruit);score=0;$('score').textContent='0';dropTier=randomSpawn();nextTier=randomSpawn();updateNextUI();gameOver=false;paused=false;resetDanger();hideMessage();clearSavedGame();sendEvent('game_reset');sendState('reset');queueSave()}
function showMessage(html){const el=$('gameMessage');el.innerHTML=html;el.hidden=false}
function hideMessage(){$('gameMessage').hidden=true}
function endGame(){if(gameOver)return;gameOver=true;resetDanger();showMessage(`FIM DE JOGO<br><small>${score.toLocaleString('pt-BR')} pontos</small>`);sendEvent('game_over',{score});sendState('gameover');queueSave()}
function setBackgroundProtection(active,{delayResume=false}={}){active=!!active;clearTimeout(backgroundResumeTimer);backgroundResumeTimer=0;if(active){if(gameOver||backgroundProtected)return false;backgroundDangerRemaining=dangerSince?Math.max(0,DANGER_HOLD_MS-(Date.now()-dangerSince)):0;backgroundProtected=true;last=performance.now();accumulator=0;showMessage('AGUARDANDO RETORNO<br><small>Partida protegida</small>');saveGame();sendEvent('background_protection',{active:true});sendState('background');return true}if(!backgroundProtected)return false;const resume=()=>{if(!backgroundProtected)return;if(dangerSince&&backgroundDangerRemaining>0){dangerSince=Date.now()-(DANGER_HOLD_MS-backgroundDangerRemaining);updateDangerHud(backgroundDangerRemaining)}backgroundProtected=false;backgroundDangerRemaining=0;last=performance.now();accumulator=0;if(gameOver)showMessage(`FIM DE JOGO<br><small>${score.toLocaleString('pt-BR')} pontos</small>`);else if(paused)showMessage('PAUSADO');else hideMessage();sendEvent('background_protection',{active:false});sendState('background');queueSave()};if(delayResume){showMessage('RETOMANDO PARTIDA<br><small>Aguarde um instante…</small>');backgroundResumeTimer=setTimeout(resume,BACKGROUND_RESUME_MS);return true}resume();return true}
function checkDanger(now){if(gameOver||paused||backgroundProtected||now-lastDangerCheck<100)return;lastDangerCheck=now;const stamp=Date.now(),candidates=fruits.filter(b=>stamp-b.spawnedAt>600&&(b.position.y+bodyRadius(b))<DANGER_Y);let candidate=null;if(dangerBodyId!==null)candidate=candidates.find(b=>b.id===dangerBodyId)||null;if(!candidate&&candidates.length)candidate=candidates.sort((a,b)=>(a.position.y+bodyRadius(a))-(b.position.y+bodyRadius(b)))[0];if(!candidate){resetDanger();return}if(dangerBodyId!==candidate.id){dangerBodyId=candidate.id;dangerSince=stamp}const elapsed=stamp-dangerSince;if(elapsed>=DANGER_HOLD_MS){endGame();return}updateDangerHud(DANGER_HOLD_MS-elapsed)}
function drawFruit(b){const t=TIERS[b.fruitTier],sprite=fruitSprites[b.fruitTier],r=t.r,pad=(sprite.width/2)-r,half=(r+pad)*(Number(b.__liveScale)||1);ctx.save();ctx.translate(b.position.x,b.position.y);ctx.rotate(b.angle);ctx.drawImage(sprite,-half,-half,half*2,half*2);ctx.restore()}
function draw(){ctx.clearRect(0,0,width,height);for(const b of fruits)drawFruit(b)}
function tick(now){const elapsed=Math.min(50,Math.max(0,now-last));last=now;if(!paused&&!backgroundProtected&&!gameOver){accumulator+=elapsed;let steps=0;while(accumulator>=FIXED_STEP&&steps<MAX_SUBSTEPS){Engine.update(engine,FIXED_STEP);enforcePlayfield();accumulator-=FIXED_STEP;steps++}if(steps===MAX_SUBSTEPS&&accumulator>FIXED_STEP)accumulator=0}else accumulator=0;checkDanger(now);draw();requestAnimationFrame(tick)}
function stateSnapshot(scope='game'){return{scope,gameId:GAME_ID,version:VERSION,score,gameOver,paused:paused||backgroundProtected,manualPaused:paused,backgroundProtected,dropTier,currentFruit:TIERS[dropTier].id,nextTier,nextFruit:TIERS[nextTier].id,fruitCount:fruits.length,highestTier:fruits.reduce((m,b)=>Math.max(m,b.fruitTier),0),dangerRemainingMs:dangerRemaining()}}
function serializableState(){return{schema:1,version:VERSION,savedAt:Date.now(),score,dropTier,nextTier,dropX,gameOver,paused,dangerRemainingMs:dangerRemaining(),fruits:fruits.map(b=>({tier:b.fruitTier,x:b.position.x,y:b.position.y,vx:b.velocity.x,vy:b.velocity.y,angle:b.angle,angularVelocity:b.angularVelocity,scale:1,spawnedAt:b.spawnedAt}))}}
function saveGame(){if(restoring)return;try{localStorage.setItem(STORAGE_KEY,JSON.stringify(serializableState()))}catch{}}
function queueSave(delay=90){if(restoring)return;clearTimeout(saveTimer);saveTimer=setTimeout(saveGame,delay)}
function restoreGame(){let data=null;try{data=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null')}catch{}if(!data||data.schema!==1||!Array.isArray(data.fruits))return false;restoring=true;try{backgroundProtected=false;backgroundDangerRemaining=0;fruits.slice().forEach(removeFruit);score=Math.max(0,Math.round(Number(data.score)||0));$('score').textContent=score.toLocaleString('pt-BR');dropTier=clamp(Number(data.dropTier)||0,0,TIERS.length-1);nextTier=clamp(Number(data.nextTier)||0,0,TIERS.length-1);dropX=Number(data.dropX)||dropX;gameOver=!!data.gameOver;paused=!!data.paused;resetDanger();for(const f of data.fruits.slice(0,300)){const tier=clamp(Number(f.tier)||0,0,TIERS.length-1),r=TIERS[tier].r,x=clamp(Number(f.x)||width/2,r,width-r),y=clamp(Number(f.y)||r,r,height-r);makeFruit(tier,x,y,{vx:Number(f.vx)||0,vy:Number(f.vy)||0,angle:Number(f.angle)||0,angularVelocity:Number(f.angularVelocity)||0,scale:clamp(Number(f.scale)||1,.2,3),spawnedAt:Number(f.spawnedAt)||Date.now()})}updateNextUI();if(gameOver)showMessage(`FIM DE JOGO<br><small>${score.toLocaleString('pt-BR')} pontos</small>`);else if(paused)showMessage('PAUSADO');else hideMessage();const rem=Math.max(0,Number(data.dangerRemainingMs)||0);if(rem>0&&!gameOver){dangerSince=Date.now()-(DANGER_HOLD_MS-rem);updateDangerHud(rem)}return true}finally{restoring=false}}
function sendState(scope='game'){window.dispatchEvent(new CustomEvent('frutas:state',{detail:{scope,state:stateSnapshot(scope)}}))}
function sendEvent(event,data={}){window.dispatchEvent(new CustomEvent('frutas:event',{detail:{gameId:GAME_ID,event,...data}}))}
function executeCommand(data={}){if(data.gameId&&String(data.gameId)!==GAME_ID)return false;const action=String(data.action||data.command||''),p=data.params&&typeof data.params==='object'?data.params:{};switch(action){case'drop_fruit':{const tier=p.tier==='random'?randomSpawn():clamp(Number(p.tier)||0,0,TIERS.length-1);return !!drop(tier,dropX,'panel')}case'set_next_fruit':nextTier=clamp(Number(p.tier)||0,0,TIERS.length-1);updateNextUI();sendState('next');queueSave();return true;case'add_score':addScore(Math.max(0,Number(p.amount)||0));return true;case'set_score':score=Math.max(0,Math.round(Number(p.amount)||0));$('score').textContent=score.toLocaleString('pt-BR');sendState('score');queueSave();return true;case'shake':{const power=clamp(Number(p.power)||4,1,10);fruits.forEach(b=>Body.applyForce(b,b.position,{x:(Math.random()-.5)*.0008*power*b.mass,y:-.00012*power*b.mass}));sendEvent('box_shaken',{power});queueSave(250);return true}case'clear_small':{const max=clamp(Number(p.maxTier)||0,0,4);fruits.slice().filter(b=>b.fruitTier<=max).forEach(removeFruit);sendState('clear');queueSave();return true}case'pause_game':if(backgroundProtected)return false;paused=!paused;if(paused)showMessage('PAUSADO');else hideMessage();sendState('pause');queueSave();return true;case'reset_game':resetGame();return true;default:return false}}
$('panelButton').onclick=()=>{$('panelModal').classList.add('show');$('panelModal').setAttribute('aria-hidden','false')};$('closePanel').onclick=()=>$('panelModal').classList.remove('show');$('panelModal').onclick=e=>{if(e.target===$('panelModal'))$('panelModal').classList.remove('show')};$('restartButton').onclick=resetGame;
function buildProgression(){$('progressionTrack').innerHTML=TIERS.map((t,i)=>`<div class="tier-pill" title="${t.name}: ${t.score} pontos"><span class="tier-swatch" style="--fruit-color:${t.color};--fruit-dark:${shade(t.color,-30)}" aria-hidden="true"></span><b>${i?`+${t.score}`:'INÍCIO'}</b></div>`).join('')}
rebuildSprites();buildProgression();updateNextUI();ensureDangerHud();resize();restoreGame();
let resizeTimer=0;const scheduleResize=()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(resize,70)};addEventListener('resize',scheduleResize,{passive:true});if('ResizeObserver'in window)new ResizeObserver(scheduleResize).observe(wrap);document.addEventListener('visibilitychange',()=>{last=performance.now();accumulator=0;if(document.visibilityState==='hidden')setBackgroundProtection(true);else setBackgroundProtection(false,{delayResume:true});scheduleResize()});addEventListener('pagehide',()=>{saveGame();setBackgroundProtection(true)},{passive:true});addEventListener('pageshow',()=>{if(document.visibilityState==='visible')setBackgroundProtection(false,{delayResume:true})},{passive:true});setInterval(()=>{if(document.visibilityState==='visible'&&!backgroundProtected)saveGame()},5000);if(document.visibilityState==='hidden')setBackgroundProtection(true);requestAnimationFrame(tick);
window.FrutasGame={version:VERSION,gameId:GAME_ID,tiers:TIERS.map(t=>({...t})),finalMergeBonus:FINAL_MERGE_BONUS,executeCommand,dropFruit:(tier,x)=>drop(tier,x??dropX,'api'),setDropX:x=>{dropX=Number(x)||dropX;updateAim()},getFieldMetrics:()=>({width,height,dpr:currentDpr,canvasCssWidth:canvas.getBoundingClientRect().width,canvasCssHeight:canvas.getBoundingClientRect().height}),reset:resetGame,getState:stateSnapshot,getBodies:()=>fruits.slice(),forceResize:resize,saveGame,restoreGame,setBackgroundProtection};
})();