(()=>{'use strict';
const C=window.FRUTAS_CONFIG||{},GAME_ID=C.gameId||'frutas',VERSION=C.version||'Beta 0.0.8',EFFECT_KEY=C.effectsStorageKey||'frutas-live-effects-v1',game=()=>window.FrutasGame,tracked=new Set();
let miniScale=1,miniExpiresAt=0,miniTimer=0,currentRules=[],rainTimer=0;
const GIANT_SCALE=[2,1.9,1.8,1.7,1.6,1.5,1.42,1.35,1.3,1.25];
const ACTIONS=[
{id:'live_restart',label:'Recomeçar',hint:'Reiniciar a partida',icon:'RST',description:'Reinicia a partida.',params:[]},
{id:'remove_points',label:'Remover pontos',hint:'Remove pontos',icon:'-PTS',description:'Remove pontos sem alterar as bolas.',params:[{id:'amount',label:'Quantidade de pontos',type:'number',min:1,max:999999999,default:Number(C.removePointsDefault)||100}]},
{id:'giant_fruit',label:'Aumenta bola aleatória',hint:'Aumenta uma bola aleatória',icon:'BIG',description:'Aumenta temporariamente uma bola que já está no campo.',params:[{id:'maxTier',label:'Tier máximo elegível',type:'number',min:0,max:9,default:5},{id:'duration',label:'Duração (segundos)',type:'number',min:1,max:300,default:20}]},
{id:'fruit_rain',label:'Chuva de bolas',hint:'Várias bolas',icon:'RAIN',description:'Solta várias bolas em sequência.',params:[{id:'count',label:'Quantidade',type:'number',min:2,max:30,default:8},{id:'maxTier',label:'Tier máximo',type:'number',min:0,max:4,default:2}]},
{id:'second_chance',label:'Segunda chance',hint:'Limpa o campo Mantém a pontuação',icon:'SAVE',description:'Limpa o campo mantendo a pontuação.',params:[]},
{id:'mini_fruits',label:'Bolas menores',hint:'Bolas 50% menores',icon:'MINI',description:'Reduz temporariamente o tamanho de todas as bolas.',params:[{id:'percent',label:'Tamanho (%)',type:'number',min:20,max:90,default:50},{id:'duration',label:'Duração (segundos)',type:'number',min:1,max:300,default:20}]}
],publicActions=ACTIONS.map(({hint,...a})=>a),byId=new Map(ACTIONS.map(a=>[a.id,a]));
function first(o,ks){for(const k of ks){const v=o?.[k];if(v!==undefined&&v!==null&&v!=='')return v}return''}
function actionId(r){return String(first(r,['actionId','action','command'])||'')}
function params(r){return r?.params||r?.actionParams||r?.effectParams||{}}
function value(r){const g=r?.gift||{};return Number(first(r,['diamondCount','giftValue','value','diamonds','coins','coinValue'])||first(g,['diamondCount','value','diamonds','coins'])||0)}
function giftName(r){const g=r?.gift||{};return String(first(r,['giftName','triggerName'])||first(g,['name','giftName','title'])||'Presente').slice(0,80)}
function giftIcon(r){const g=r?.gift||{};return String(first(r,['giftIcon','giftImage','icon','image'])||first(g,['icon','image','iconUrl','imageUrl','pictureUrl'])||'')}
function safeImageUrl(raw){try{const u=new URL(String(raw||''),location.href);return ['https:','http:'].includes(u.protocol)&&u.href.length<2048?u.href:''}catch{return''}}
function duration(p,fallback=0){const raw=first(p,['duration','durationSeconds','seconds','time','tempo']),n=Number(raw||fallback);return Number.isFinite(n)&&n>0?Math.round(n):0}
function maxTierParam(p,fallback=5){const raw=first(p,['maxTier','tierMax','tier']);const n=raw===''?fallback:Number(raw);return Math.max(0,Math.min(9,Number.isFinite(n)?Math.round(n):fallback))}
function effect(a,p){if(a==='remove_points')return'Remove '+Math.max(0,Number(p.amount)||0).toLocaleString('pt-BR')+' pontos';if(a==='fruit_rain')return'Chuva de '+Math.max(2,Number(p.count)||8)+' bolas';if(a==='mini_fruits'){const size=Math.max(20,Math.min(90,Number(p.percent)||50)),smaller=Math.max(0,100-size),d=duration(p,20);return'Bolas '+smaller+'% menores'+(d?' '+d+'s':'')}if(a==='giant_fruit'){const d=duration(p,20);return'Aumenta uma bola aleatória'+(d?' '+d+'s':'')}if(a==='second_chance')return'Limpa o campo Mantém a pontuação';if(a==='live_restart')return'Reiniciar a partida';return byId.get(a)?.description||a}
function addPanel(){const footer=document.querySelector('.statusbar');if(!footer||document.querySelector('.live-actions'))return;const box=document.createElement('section');box.className='live-actions';footer.before(box);render([]);requestAnimationFrame(()=>game()?.forceResize?.())}
function card(a,r){const outer=document.createElement('div');outer.className='live-action-card'+(r?'':' empty');const gift=document.createElement('div');gift.className='live-gift';const span=document.createElement('span');if(r){const src=safeImageUrl(giftIcon(r));if(src){const img=document.createElement('img');img.src=src;img.alt='';img.referrerPolicy='no-referrer';gift.appendChild(img)}else{span.textContent='SEM FOTO';gift.appendChild(span)}}else{span.textContent='SEM REGRA';gift.appendChild(span)}const copy=document.createElement('div');copy.className='live-copy';const b=document.createElement('b');b.textContent=r?giftName(r):a.label;const small=document.createElement('small');small.textContent=r?effect(a.id,params(r)):a.hint;copy.append(b,small);outer.append(gift,copy);return outer}
function render(rules=currentRules){currentRules=Array.isArray(rules)?rules:[];const box=document.querySelector('.live-actions');if(!box)return;const map=new Map();for(const r of currentRules){const id=actionId(r);if(byId.has(id)&&!map.has(id))map.set(id,r)}const ordered=[...ACTIONS].sort((a,b)=>{const ra=map.get(a.id),rb=map.get(b.id);if(ra&&!rb)return-1;if(!ra&&rb)return 1;if(ra&&rb)return value(ra)-value(rb);return ACTIONS.indexOf(a)-ACTIONS.indexOf(b)});box.replaceChildren();const title=document.createElement('div');title.className='live-actions-title';title.textContent='INTERAÇÕES DA LIVE';box.appendChild(title);for(const a of ordered)box.appendChild(card(a,map.get(a.id)));requestAnimationFrame(()=>game()?.forceResize?.())}
function loadEffectState(){try{const s=JSON.parse(localStorage.getItem(EFFECT_KEY)||'null');if(Number(s?.miniScale)>=.2&&Number(s?.miniScale)<1&&Number(s?.miniExpiresAt)>Date.now()){miniScale=Number(s.miniScale);miniExpiresAt=Number(s.miniExpiresAt)}}catch{}}
function saveEffectState(){try{if(miniScale<1&&miniExpiresAt>Date.now())localStorage.setItem(EFFECT_KEY,JSON.stringify({schema:1,miniScale,miniExpiresAt}));else localStorage.removeItem(EFFECT_KEY)}catch{}}
function track(){for(const b of game()?.getBodies?.()||[]){tracked.add(b);const current=Math.max(.05,Number(b.__liveScale)||1);b.__liveScale=current;if(!Number(b.__liveBaseScale))b.__liveBaseScale=miniScale<1?current/miniScale:current}}
function patchMatter(){if(!window.Matter?.World||window.__FRUTAS_TRACK_PATCHED__)return;window.__FRUTAS_TRACK_PATCHED__=true;track();const W=Matter.World,add=W.add.bind(W),remove=W.remove.bind(W);W.add=function(world,obj){const out=add(world,obj);for(const b of(Array.isArray(obj)?obj:[obj]))if(b?.label==='fruit'){tracked.add(b);b.__liveBaseScale=Number(b.__liveBaseScale)||1;b.__liveScale=Number(b.__liveScale)||1;if(miniScale!==1){Matter.Body.scale(b,miniScale,miniScale);b.__liveScale*=miniScale}}return out};W.remove=function(world,obj,...rest){tracked.delete(obj);return remove(world,obj,...rest)}}
function scaleTo(b,target){const now=Math.max(.05,Number(b.__liveScale)||1),next=Math.max(.05,target);Matter.Body.scale(b,next/now,next/now);b.__liveScale=next}
function setMini(scale,ms){miniScale=Math.max(.2,Math.min(1,Number(scale)||1));miniExpiresAt=miniScale<1&&ms>0?Date.now()+ms:0;track();for(const b of tracked)scaleTo(b,(Number(b.__liveBaseScale)||1)*miniScale);clearTimeout(miniTimer);if(miniExpiresAt>Date.now())miniTimer=setTimeout(()=>setMini(1,0),miniExpiresAt-Date.now());saveEffectState();game()?.saveGame?.()}
function clearMini(){setMini(1,0)}
function restoreMini(){track();if(miniScale<1&&miniExpiresAt>Date.now()){for(const b of tracked)scaleTo(b,(Number(b.__liveBaseScale)||1)*miniScale);clearTimeout(miniTimer);miniTimer=setTimeout(()=>setMini(1,0),miniExpiresAt-Date.now())}else if(miniScale<1)clearMini()}
function stopRain(){clearInterval(rainTimer);rainTimer=0}
function cancelAll(){stopRain();clearMini()}
function giantScale(tier){return GIANT_SCALE[Math.max(0,Math.min(9,Number(tier)||0))]||1.25}
function growExistingGiant(api,p){track();const maxTier=maxTierParam(p,5),seconds=Math.max(1,Math.min(300,duration(p,20))),now=Date.now(),eligible=(api.getBodies?.()||[]).filter(b=>b?.label==='fruit'&&Number(b.fruitTier)<=maxTier&&!b.mergeLock&&!(Number(b.__giantExpiresAt)>now));if(!eligible.length)return false;const b=eligible[(Math.random()*eligible.length)|0],target=giantScale(b.fruitTier),startBase=Math.max(.05,Number(b.__liveBaseScale)||1),growMs=Math.min(1200,Math.max(350,seconds*1000*.18)),started=performance.now(),expiresAt=now+seconds*1000;b.__giantExpiresAt=expiresAt;const step=t=>{if(!tracked.has(b)||b.mergeLock||b.__giantExpiresAt!==expiresAt)return;const q=Math.min(1,(t-started)/growMs),ease=1-Math.pow(1-q,3),base=startBase+(target-startBase)*ease;b.__liveBaseScale=base;scaleTo(b,base*miniScale);if(q<1)requestAnimationFrame(step)};requestAnimationFrame(step);setTimeout(()=>{if(!tracked.has(b)||b.__giantExpiresAt!==expiresAt)return;b.__giantExpiresAt=0;b.__liveBaseScale=1;scaleTo(b,miniScale);api.saveGame?.()},seconds*1000);api.saveGame?.();return true}
function executeRaw(data={}){const action=String(data.action||data.command||''),p=data.params&&typeof data.params==='object'?data.params:{},api=game();if(!api)return false;switch(action){case'live_restart':cancelAll();api.reset();break;case'remove_points':{const s=api.getState?.()||{};api.executeCommand({action:'set_score',params:{amount:Math.max(0,(Number(s.score)||0)-Math.max(0,Number(p.amount)||0))}});break}case'giant_fruit':return growExistingGiant(api,p);case'fruit_rain':{stopRain();const count=Math.max(2,Math.min(30,Number(p.count)||8)),maxTier=Math.max(0,Math.min(4,Number(p.maxTier)||2));let i=0;rainTimer=setInterval(()=>{if(i++>=count){stopRain();return}const m=api.getFieldMetrics?.()||{},w=Number(m.width)||360;api.dropFruit(Math.floor(Math.random()*(maxTier+1)),30+Math.random()*Math.max(1,w-60))},330);break}case'second_chance':{cancelAll();const pts=Number(api.getState?.().score)||0;api.reset();api.executeCommand({action:'set_score',params:{amount:pts}});break}case'mini_fruits':setMini(Math.max(20,Math.min(90,Number(p.percent)||50))/100,Math.max(1,Math.min(300,duration(p,20)))*1000);break;default:return false}return true}
async function execute(data={}){const mgr=window.FrutasActionManager;if(!mgr)return executeRaw(data);return (await mgr.run(data,executeRaw)).ok}
loadEffectState();patchMatter();restoreMini();addPanel();
window.addEventListener('frutas:rules_sync',e=>render(e.detail?.rules||[]));window.addEventListener('frutas:reset',cancelAll);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')restoreMini()});
window.FrutasLiveActions={version:VERSION,actions:publicActions,execute,executeRaw,syncRules:render,getMiniScale:()=>miniScale,getMiniExpiresAt:()=>miniExpiresAt,stopRain,clearMini,cancelAll};
})();