(()=>{'use strict';
const C=window.FRUTAS_CONFIG||{},GAME_ID=C.gameId||'frutas',VERSION=C.version||'Beta 0.0.8',EFFECT_KEY=C.effectsStorageKey||'frutas-live-effects-v1',game=()=>window.FrutasGame,tracked=new Set();
let miniScale=1,miniExpiresAt=0,miniTimer=0,currentRules=[],rainTimer=0;
const ACTIONS=[
{id:'live_restart',label:'Recomeçar',hint:'Reiniciar a partida',icon:'RST',description:'Zera frutas e pontos e reinicia a partida.',params:[]},
{id:'remove_points',label:'Remover pontos',hint:'mantém a partida',icon:'-PTS',description:'Remove pontos sem alterar as frutas.',params:[{id:'amount',label:'Quantidade de pontos',type:'number',min:1,max:999999999,default:Number(C.removePointsDefault)||100}]},
{id:'giant_fruit',label:'Fruta gigante',hint:'Fruta gigante',icon:'BIG',description:'Solta uma fruta ampliada.',params:[{id:'tier',label:'Nível da fruta',type:'number',min:0,max:9,default:4},{id:'scale',label:'Tamanho',type:'number',min:1.1,max:3,default:1.8}]},
{id:'fruit_rain',label:'Chuva de frutas',hint:'várias frutas',icon:'RAIN',description:'Solta várias frutas em sequência.',params:[{id:'count',label:'Quantidade',type:'number',min:2,max:30,default:8},{id:'maxTier',label:'Nível máximo',type:'number',min:0,max:4,default:2}]},
{id:'second_chance',label:'Segunda chance',hint:'Limpa e mantém pontos',icon:'SAVE',description:'Limpa a caixa mantendo a pontuação.',params:[]},
{id:'mini_fruits',label:'Mini frutas',hint:'tamanho temporário',icon:'MINI',description:'Reduz fisicamente todas as frutas.',params:[{id:'percent',label:'Tamanho (%)',type:'number',min:20,max:90,default:50},{id:'duration',label:'Duração (segundos)',type:'number',min:1,max:300,default:20}]}
],publicActions=ACTIONS.map(({hint,...a})=>a),byId=new Map(ACTIONS.map(a=>[a.id,a]));
function first(o,ks){for(const k of ks){const v=o?.[k];if(v!==undefined&&v!==null&&v!=='')return v}return''}
function actionId(r){return String(first(r,['actionId','action','command'])||'')}
function params(r){return r?.params||r?.actionParams||r?.effectParams||{}}
function value(r){const g=r?.gift||{};return Number(first(r,['diamondCount','giftValue','value','diamonds','coins','coinValue'])||first(g,['diamondCount','value','diamonds','coins'])||0)}
function giftName(r){const g=r?.gift||{};return String(first(r,['giftName','triggerName'])||first(g,['name','giftName','title'])||'Presente').slice(0,80)}
function giftIcon(r){const g=r?.gift||{};return String(first(r,['giftIcon','giftImage','icon','image'])||first(g,['icon','image','iconUrl','imageUrl','pictureUrl'])||'')}
function safeImageUrl(raw){try{const u=new URL(String(raw||''),location.href);return ['https:','http:'].includes(u.protocol)&&u.href.length<2048?u.href:''}catch{return''}}
function duration(p){const n=Number(first(p,['duration','durationSeconds','seconds','time','tempo']));return Number.isFinite(n)&&n>0?Math.round(n)+'s':''}
function withDuration(text,p){const d=duration(p);return d?text+' · '+d:text}
function effect(a,p){if(a==='remove_points')return'Remove '+Math.max(0,Number(p.amount)||0).toLocaleString('pt-BR')+' pontos';if(a==='fruit_rain')return'Chuva com '+Math.max(2,Number(p.count)||8)+' frutas';if(a==='mini_fruits')return withDuration(Math.max(20,Number(p.percent)||50)+'% do tamanho',p);if(a==='giant_fruit')return withDuration('Fruta gigante',p);if(a==='second_chance')return'Limpa e mantém pontos';if(a==='live_restart')return'Reiniciar a partida';return byId.get(a)?.description||a}
function addPanel(){const footer=document.querySelector('.statusbar');if(!footer||document.querySelector('.live-actions'))return;const box=document.createElement('section');box.className='live-actions';footer.before(box);render([]);requestAnimationFrame(()=>game()?.forceResize?.())}
function card(a,r){const outer=document.createElement('div');outer.className='live-action-card'+(r?'':' empty');const gift=document.createElement('div');gift.className='live-gift';const span=document.createElement('span');if(r){const src=safeImageUrl(giftIcon(r));if(src){const img=document.createElement('img');img.src=src;img.alt='';img.referrerPolicy='no-referrer';gift.appendChild(img)}else{span.textContent='SEM FOTO';gift.appendChild(span)}}else{span.textContent='SEM REGRA';gift.appendChild(span)}const copy=document.createElement('div');copy.className='live-copy';const b=document.createElement('b');b.textContent=r?giftName(r):a.label;const small=document.createElement('small');small.textContent=r?effect(a.id,params(r)):a.hint;copy.append(b,small);outer.append(gift,copy);return outer}
function render(rules=currentRules){currentRules=Array.isArray(rules)?rules:[];const box=document.querySelector('.live-actions');if(!box)return;const map=new Map();for(const r of currentRules){const id=actionId(r);if(byId.has(id)&&!map.has(id))map.set(id,r)}const ordered=[...ACTIONS].sort((a,b)=>{const ra=map.get(a.id),rb=map.get(b.id);if(ra&&!rb)return-1;if(!ra&&rb)return 1;if(ra&&rb)return value(ra)-value(rb);return ACTIONS.indexOf(a)-ACTIONS.indexOf(b)});box.replaceChildren();const title=document.createElement('div');title.className='live-actions-title';title.textContent='INTERAÇÕES DA LIVE';box.appendChild(title);for(const a of ordered)box.appendChild(card(a,map.get(a.id)));requestAnimationFrame(()=>game()?.forceResize?.())}
function loadEffectState(){try{const s=JSON.parse(localStorage.getItem(EFFECT_KEY)||'null');if(Number(s?.miniScale)>=.2&&Number(s?.miniScale)<1&&Number(s?.miniExpiresAt)>Date.now()){miniScale=Number(s.miniScale);miniExpiresAt=Number(s.miniExpiresAt)}}catch{}}
function saveEffectState(){try{if(miniScale<1&&miniExpiresAt>Date.now())localStorage.setItem(EFFECT_KEY,JSON.stringify({schema:1,miniScale,miniExpiresAt}));else localStorage.removeItem(EFFECT_KEY)}catch{}}
function track(){for(const b of game()?.getBodies?.()||[]){tracked.add(b);const current=Math.max(.05,Number(b.__liveScale)||1);b.__liveScale=current;if(!Number(b.__liveBaseScale))b.__liveBaseScale=miniScale<1?current/miniScale:current}}
function patchMatter(){if(!window.Matter?.World||window.__FRUTAS_TRACK_PATCHED__)return;window.__FRUTAS_TRACK_PATCHED__=true;track();const W=Matter.World,add=W.add.bind(W),remove=W.remove.bind(W);W.add=function(world,obj){const out=add(world,obj);for(const b of(Array.isArray(obj)?obj:[obj]))if(b?.label==='fruit'){tracked.add(b);b.__liveBaseScale=Number(b.__liveBaseScale)||1;b.__liveScale=Number(b.__liveScale)||1;if(miniScale!==1){Matter.Body.scale(b,miniScale,miniScale);b.__liveScale*=miniScale}}return out};W.remove=function(world,obj,...rest){tracked.delete(obj);return remove(world,obj,...rest)}}
function scaleTo(b,target){const now=Math.max(.05,Number(b.__liveScale)||1),next=Math.max(.05,target);Matter.Body.scale(b,next/now,next/now);b.__liveScale=next}
function setMini(scale,ms){miniScale=Math.max(.2,Math.min(1,Number(scale)||1));miniExpiresAt=miniScale<1&&ms>0?Date.now()+ms:0;track();for(const b of tracked)scaleTo(b,(Number(b.__liveBaseScale)||1)*miniScale);clearTimeout(miniTimer);if(miniExpiresAt>Date.now())miniTimer=setTimeout(()=>setMini(1,0),miniExpiresAt-Date.now());saveEffectState();game()?.saveGame?.()}
function clearMini(){setMini(1,0)}
function restoreMini(){track();if(miniScale<1&&miniExpiresAt>Date.now()){for(const b of tracked)scaleTo(b,(Number(b.__liveBaseScale)||1)*miniScale);clearTimeout(miniTimer);miniTimer=setTimeout(()=>setMini(1,0),miniExpiresAt-Date.now())}else if(miniScale<1)clearMini()}
function stopRain(){clearInterval(rainTimer);rainTimer=0}
function cancelAll(){stopRain();clearMini()}
function executeRaw(data={}){const action=String(data.action||data.command||''),p=data.params&&typeof data.params==='object'?data.params:{},api=game();if(!api)return false;switch(action){case'live_restart':cancelAll();api.reset();break;case'remove_points':{const s=api.getState?.()||{};api.executeCommand({action:'set_score',params:{amount:Math.max(0,(Number(s.score)||0)-Math.max(0,Number(p.amount)||0))}});break}case'giant_fruit':{const m=api.getFieldMetrics?.()||{},tier=Math.max(0,Math.min(9,Number(p.tier)||4)),scale=Math.max(1.1,Math.min(3,Number(p.scale)||1.8)),w=Number(m.width)||360,b=api.dropFruit(tier,w*(.25+Math.random()*.5));if(b){b.__liveBaseScale=scale;scaleTo(b,scale*miniScale);api.saveGame?.()}break}case'fruit_rain':{stopRain();const count=Math.max(2,Math.min(30,Number(p.count)||8)),maxTier=Math.max(0,Math.min(4,Number(p.maxTier)||2));let i=0;rainTimer=setInterval(()=>{if(i++>=count){stopRain();return}const m=api.getFieldMetrics?.()||{},w=Number(m.width)||360;api.dropFruit(Math.floor(Math.random()*(maxTier+1)),30+Math.random()*Math.max(1,w-60))},330);break}case'second_chance':{cancelAll();const pts=Number(api.getState?.().score)||0;api.reset();api.executeCommand({action:'set_score',params:{amount:pts}});break}case'mini_fruits':setMini(Math.max(20,Math.min(90,Number(p.percent)||50))/100,Math.max(1,Math.min(300,Number(p.duration)||20))*1000);break;default:return false}return true}
async function execute(data={}){const mgr=window.FrutasActionManager;if(!mgr)return executeRaw(data);return (await mgr.run(data,executeRaw)).ok}
loadEffectState();patchMatter();restoreMini();addPanel();
window.addEventListener('frutas:rules_sync',e=>render(e.detail?.rules||[]));window.addEventListener('frutas:reset',cancelAll);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')restoreMini()});
window.FrutasLiveActions={version:VERSION,actions:publicActions,execute,executeRaw,syncRules:render,getMiniScale:()=>miniScale,getMiniExpiresAt:()=>miniExpiresAt,stopRain,clearMini,cancelAll};
})();