(()=>{'use strict';
const C=window.FRUTAS_CONFIG||{},GAME_ID=C.gameId||'frutas',VERSION=C.version||'Beta 0.0.8';let session=null,rules=[],busy=false,timer=0,lastSignature='',pendingCommands=[],flushTimer=0;
const $=id=>document.getElementById(id),clean=v=>String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,8),format=v=>{const c=clean(v);return c.length>4?c.slice(0,4)+'-'+c.slice(4):c};
function status(text,kind=''){const p=$('pairMessage'),s=$('panelStatus'),d=$('statusDot');if(p){p.textContent=text;p.className='pair-message '+kind}if(s)s.textContent=text;if(d)d.className=kind}
function manifest(){return{protocol:'liveplus-game-manifest-v1',gameId:GAME_ID,name:'Frutas · Merge Live',icon:'FR',version:VERSION,actions:[...(window.FrutasLiveActions?.actions||[])],adminTools:[...(window.FrutasAutoPlayer?.adminTools||[])]}}
function state(scope='game'){const s=window.FrutasGame?.getState?.(scope)||{};return{...s,scope,gameId:GAME_ID,version:VERSION,transport:session?.getTransport?.()||'offline',rules:rules.length,pendingLiveCommands:pendingCommands.length,autoPlayer:window.FrutasAutoPlayer?.getState?.()||null}}
function sendState(scope='game'){try{session?.sendState?.(state(scope))}catch{}}
function sendEvent(data={}){try{session?.sendEvent?.({gameId:GAME_ID,...data})}catch{}}
function syncState(){if((session?.getTransport?.()||'offline')==='offline')return;const s=state('game'),a=s.autoPlayer||{},sig=[s.score,s.gameOver,s.paused,s.backgroundProtected,s.dropTier,s.nextTier,s.fruitCount,s.highestTier,s.dangerRemainingMs,s.pendingLiveCommands,a.enabled,a.intervalMs,a.stats?.drops,a.stats?.highestScore].join('|');if(sig!==lastSignature){lastSignature=sig;try{session.sendState(s)}catch{}}}
function isAdmin(data={}){return data.admin===true||data.channel==='admin'}
function gameProtected(){const s=window.FrutasGame?.getState?.()||{};return document.visibilityState==='hidden'||s.backgroundProtected===true}
async function executeCommand(data={}){let ok=false;if(isAdmin(data))ok=!!(await window.FrutasAutoPlayer?.executeAdmin?.(data));else ok=!!(await window.FrutasLiveActions?.execute?.(data));try{session?.sendState?.({scope:'command',gameId:GAME_ID,version:VERSION,commandStatus:ok?'executed':'unsupported',action:String(data.action||data.command||''),admin:isAdmin(data),pendingLiveCommands:pendingCommands.length,autoPlayer:window.FrutasAutoPlayer?.getState?.()||null})}catch{}syncState();return ok}
function queueCommand(data){pendingCommands.push(data);try{session?.sendState?.({scope:'command',gameId:GAME_ID,version:VERSION,commandStatus:'queued',action:String(data.action||data.command||''),admin:false,pendingLiveCommands:pendingCommands.length})}catch{}syncState()}
async function flushPending(){clearTimeout(flushTimer);flushTimer=0;if(!pendingCommands.length)return;if(gameProtected()){flushTimer=setTimeout(flushPending,180);return}while(pendingCommands.length&&!gameProtected()){const data=pendingCommands.shift();await executeCommand(data);await new Promise(r=>setTimeout(r,120))}syncState();if(pendingCommands.length)flushTimer=setTimeout(flushPending,180)}
async function onCommand(data={}){if(!isAdmin(data)&&gameProtected()){queueCommand(data);return}await executeCommand(data)}
async function connect(codeInput){const input=$('panelCode'),code=clean(codeInput||input?.value);if(input)input.value=format(code);if(code.length!==8){status('Código inválido','err');return false}if(!window.LivePlusGameSDK?.Session){status('SDK LIVE+ não carregou','err');return false}try{session?.disconnect?.()}catch{}session=new LivePlusGameSDK.Session({storageKey:C.panelStorageKey||'frutas-liveplus-token',manifest:manifest()});session.addEventListener('connected',()=>{status('Painel conectado','ok');lastSignature='';sendState('initial');setTimeout(()=>$('panelModal')?.classList.remove('show'),300)});session.addEventListener('command',e=>onCommand(e.detail||{}));session.addEventListener('message',e=>{const d=e.detail||{};if(d.type==='rules_sync'&&Array.isArray(d.rules)){rules=d.rules;window.dispatchEvent(new CustomEvent('frutas:rules_sync',{detail:{rules}}));sendState('rules')}});session.addEventListener('reconnecting',()=>status('Reconectando…','warn'));session.addEventListener('lost',()=>status('Conexão perdida','err'));session.addEventListener('rejected',e=>status(e.detail?.reason||'Sessão recusada','err'));status('Conectando…','warn');try{localStorage.setItem(C.panelCodeKey||'frutas-panel-code',format(code))}catch{}try{await session.connect(code);return true}catch(err){status(err?.message||'Falha ao conectar','err');return false}}
function savedCode(){try{return clean(localStorage.getItem(C.panelCodeKey||'frutas-panel-code'))}catch{return''}}
async function reconnect(){clearTimeout(timer);const code=savedCode();if(code.length!==8||busy||(session?.getTransport?.()||'offline')!=='offline')return;busy=true;try{await connect(code)}finally{timer=setTimeout(()=>{busy=false},1200)}}
function schedule(ms=250){clearTimeout(timer);timer=setTimeout(reconnect,ms)}
function bind(){const btn=$('connectPanel'),input=$('panelCode');if(btn)btn.onclick=()=>connect();if(input){const saved=savedCode();if(saved)input.value=format(saved);input.oninput=e=>e.target.value=format(e.target.value);input.onkeydown=e=>{if(e.key==='Enter')connect()}}const api=window.FrutasGame;if(api&&!api.__panelBridgeStatePatched){api.__panelBridgeStatePatched=true;const original=api.getState.bind(api);api.getState=(...args)=>({...original(...args),transport:session?.getTransport?.()||'offline',rules:rules.length,pendingLiveCommands:pendingCommands.length});api.connectPanel=connect}}
bind();schedule(180);setInterval(syncState,500);window.addEventListener('frutas:event',e=>{sendEvent(e.detail||{});if(e.detail?.event==='background_protection'&&e.detail?.active===false)setTimeout(flushPending,60)});window.addEventListener('frutas:state',e=>{const scope=e.detail?.scope||'game';sendState(scope)});window.addEventListener('pageshow',()=>{schedule(180);setTimeout(flushPending,1400)});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){schedule(350);setTimeout(flushPending,1400)}});
window.FrutasPanelBridge={connect,reconnect,sendState,sendEvent,syncState,getSession:()=>session,getRules:()=>rules.slice(),getTransport:()=>session?.getTransport?.()||'offline',getPendingCommands:()=>pendingCommands.slice(),flushPending,manifest};
})();