(()=>{'use strict';
const C=window.FRUTAS_CONFIG||{},GAME_ID=C.gameId||'frutas',VERSION=C.version||'Beta 0.0.8',HUD_KEY=C.hudVisibleKey||'frutas-live-hud-visible',QUEUE_KEY=C.liveQueueKey||'frutas-live-queue-v1';
const QUEUE_TTL=15*60*1000,QUEUE_MAX=100,PRESENCE_TIMEOUT=10000;
let session=null,rules=[],busy=false,timer=0,lastSignature='',pendingCommands=[],flushTimer=0,lastPanelSeen=0,panelPresent=false;
const $=id=>document.getElementById(id),clean=v=>String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,8),format=v=>{const c=clean(v);return c.length>4?c.slice(0,4)+'-'+c.slice(4):c};
function resolveConnection(raw=''){const text=String(raw||'').trim(),sdk=window.LivePlusGameSDK,ticket=sdk?.parseTicket?.(text)||null;if(ticket){sdk.configureRelay?.(ticket.endpoint);return{code:clean(ticket.code),value:text,ticket:true}}const code=clean(text);return{code,value:code,ticket:false}}
function eventId(data={}){return String(data.commandId||data.eventId||data.deliveryId||data.id||data.messageId||'').trim()}
function status(text,kind=''){const p=$('pairMessage'),s=$('panelStatus'),d=$('statusDot');if(p){p.textContent=text;p.className='pair-message '+kind}if(s)s.textContent=text;if(d)d.className=kind}
function markPanelPresent(){lastPanelSeen=Date.now();if(!panelPresent){panelPresent=true;status('Painel conectado','ok');lastSignature='';syncState()}}
function markPanelOffline(text='Painel offline'){if(!panelPresent&&$('panelStatus')?.textContent===text)return;panelPresent=false;lastPanelSeen=0;status(text,'');lastSignature=''}
function checkPanelPresence(){const transport=session?.getTransport?.()||'offline';if(transport==='offline'){if(panelPresent)markPanelOffline();return}if(panelPresent&&Date.now()-lastPanelSeen>PRESENCE_TIMEOUT)markPanelOffline()}
function savedHudVisible(){try{return localStorage.getItem(HUD_KEY)==='1'}catch{return false}}
function setHudVisible(active,{persist=true}={}){const visible=!!active,box=document.querySelector('.live-actions'),toggle=$('liveHudToggle');if(box)box.hidden=!visible;if(toggle)toggle.checked=visible;if(persist){try{localStorage.setItem(HUD_KEY,visible?'1':'0')}catch{}}requestAnimationFrame(()=>window.FrutasGame?.forceResize?.());setTimeout(()=>window.FrutasGame?.forceResize?.(),90);return visible}
function pruneQueue(){const now=Date.now();pendingCommands=pendingCommands.filter(x=>x&&x.data&&now-(Number(x.queuedAt)||now)<=QUEUE_TTL).slice(-QUEUE_MAX)}
function saveQueue(){pruneQueue();try{if(pendingCommands.length)localStorage.setItem(QUEUE_KEY,JSON.stringify({schema:1,savedAt:Date.now(),items:pendingCommands}));else localStorage.removeItem(QUEUE_KEY)}catch{}}
function loadQueue(){try{const raw=JSON.parse(localStorage.getItem(QUEUE_KEY)||'null');pendingCommands=Array.isArray(raw?.items)?raw.items:[]}catch{pendingCommands=[]}pruneQueue();saveQueue()}
function queuedAlready(data){const id=eventId(data);return !!id&&pendingCommands.some(x=>eventId(x.data)===id)}
function manifest(){return{protocol:'liveplus-game-manifest-v1',gameId:GAME_ID,name:'Frutas · Merge Live',icon:'FR',version:VERSION,actions:[...(window.FrutasLiveActions?.actions||[])],adminTools:[...(window.FrutasAutoPlayer?.adminTools||[])]}}
function state(scope='game'){const s=window.FrutasGame?.getState?.(scope)||{};return{...s,scope,gameId:GAME_ID,version:VERSION,transport:session?.getTransport?.()||'offline',panelPresent,rules:rules.length,pendingLiveCommands:pendingCommands.length,hudVisible:savedHudVisible(),autoPlayer:window.FrutasAutoPlayer?.getState?.()||null}}
function sendState(scope='game'){try{session?.sendState?.(state(scope))}catch{}}
function sendEvent(data={}){try{session?.sendEvent?.({gameId:GAME_ID,...data})}catch{}}
function syncState(){if((session?.getTransport?.()||'offline')==='offline')return;const s=state('game'),a=s.autoPlayer||{},sig=[s.score,s.gameOver,s.paused,s.backgroundProtected,s.dropTier,s.nextTier,s.fruitCount,s.highestTier,s.dangerRemainingMs,s.pendingLiveCommands,s.hudVisible,s.panelPresent,a.enabled,a.intervalMs,a.stats?.drops,a.stats?.highestScore].join('|');if(sig!==lastSignature){lastSignature=sig;try{session.sendState(s)}catch{}}}
function isAdmin(data={}){return data.admin===true||data.channel==='admin'}
function knownAction(data={}){const id=String(data.action||data.command||'');if(isAdmin(data))return (window.FrutasAutoPlayer?.adminTools||[]).some(a=>a.id===id);return (window.FrutasLiveActions?.actions||[]).some(a=>a.id===id)}
function gameProtected(){const s=window.FrutasGame?.getState?.()||{};return document.visibilityState==='hidden'||s.backgroundProtected===true}
async function executeCommand(data={}){markPanelPresent();let ok=false;if(isAdmin(data))ok=!!(await window.FrutasAutoPlayer?.executeAdmin?.(data));else ok=!!(await window.FrutasLiveActions?.execute?.(data));try{session?.sendState?.({scope:'command',gameId:GAME_ID,version:VERSION,commandStatus:ok?'executed':'unsupported',action:String(data.action||data.command||''),admin:isAdmin(data),pendingLiveCommands:pendingCommands.length,autoPlayer:window.FrutasAutoPlayer?.getState?.()||null})}catch{}syncState();return ok}
function queueCommand(data){markPanelPresent();if(queuedAlready(data)){syncState();return false}pendingCommands.push({queuedAt:Date.now(),data});pruneQueue();saveQueue();try{session?.sendState?.({scope:'command',gameId:GAME_ID,version:VERSION,commandStatus:'queued',action:String(data.action||data.command||''),admin:false,pendingLiveCommands:pendingCommands.length})}catch{}syncState();return true}
async function flushPending(){clearTimeout(flushTimer);flushTimer=0;pruneQueue();saveQueue();if(!pendingCommands.length)return;if(gameProtected()){flushTimer=setTimeout(flushPending,180);return}while(pendingCommands.length&&!gameProtected()){const item=pendingCommands[0];if(!knownAction(item.data)){pendingCommands.shift();saveQueue();continue}try{const ok=await executeCommand(item.data);if(ok){pendingCommands.shift();saveQueue()}else{saveQueue();flushTimer=setTimeout(flushPending,800);return}}catch{saveQueue();flushTimer=setTimeout(flushPending,800);return}await new Promise(r=>setTimeout(r,120))}syncState();if(pendingCommands.length)flushTimer=setTimeout(flushPending,180)}
async function onCommand(data={}){markPanelPresent();if(!isAdmin(data)&&gameProtected()){queueCommand(data);return}await executeCommand(data)}
async function connect(codeInput){const input=$('panelCode');if(!window.LivePlusGameSDK?.Session){status('SDK LIVE+ não carregou','err');return false}const raw=codeInput??input?.value??'',target=resolveConnection(raw),code=target.code;if(input)input.value=format(code);if(code.length!==8){status('Código inválido','err');return false}try{session?.disconnect?.()}catch{}panelPresent=false;lastPanelSeen=0;session=new LivePlusGameSDK.Session({storageKey:C.panelStorageKey||'frutas-liveplus-token',manifest:manifest()});session.addEventListener('connected',e=>{const d=e.detail||{};if(d.transport==='peer'||d.panelConnected===true)markPanelPresent();else status('Aguardando painel…','warn');lastSignature='';sendState('initial');setTimeout(flushPending,120);setTimeout(()=>$('panelModal')?.classList.remove('show'),300)});session.addEventListener('command',e=>onCommand(e.detail||{}));session.addEventListener('message',e=>{const d=e.detail||{};markPanelPresent();if(d.type==='panel_heartbeat')return;if(d.type==='rules_sync'&&Array.isArray(d.rules)){rules=d.rules;window.dispatchEvent(new CustomEvent('frutas:rules_sync',{detail:{rules}}));sendState('rules')}});session.addEventListener('reconnecting',()=>{panelPresent=false;lastPanelSeen=0;status('Reconectando…','warn')});session.addEventListener('lost',()=>markPanelOffline('Conexão perdida'));session.addEventListener('rejected',e=>{panelPresent=false;lastPanelSeen=0;status(e.detail?.reason||'Sessão recusada','err')});status('Conectando…','warn');try{localStorage.setItem(C.panelCodeKey||'frutas-panel-code',format(code))}catch{}try{await session.connect(target.value);return true}catch(err){panelPresent=false;lastPanelSeen=0;status(err?.message||'Falha ao conectar','err');return false}}
function savedCode(){try{return clean(localStorage.getItem(C.panelCodeKey||'frutas-panel-code'))}catch{return''}}
async function reconnect(){clearTimeout(timer);const code=savedCode();if(code.length!==8||busy||(session?.getTransport?.()||'offline')!=='offline')return;busy=true;try{await connect(code)}finally{timer=setTimeout(()=>{busy=false},1200)}}
function schedule(ms=250){clearTimeout(timer);timer=setTimeout(reconnect,ms)}
function bind(){const btn=$('connectPanel'),input=$('panelCode'),hud=$('liveHudToggle');if(btn)btn.onclick=()=>connect();if(input){window.LivePlusGameSDK?.installPasteBridge?.(input);const saved=savedCode();if(saved)input.value=format(saved);input.oninput=e=>e.target.value=format(e.target.value);input.onkeydown=e=>{if(e.key==='Enter')connect()}}if(hud)hud.onchange=e=>{setHudVisible(e.target.checked);lastSignature='';syncState()};setHudVisible(savedHudVisible(),{persist:false});const api=window.FrutasGame;if(api&&!api.__panelBridgeStatePatched){api.__panelBridgeStatePatched=true;const original=api.getState.bind(api);api.getState=(...args)=>({...original(...args),transport:session?.getTransport?.()||'offline',panelPresent,rules:rules.length,pendingLiveCommands:pendingCommands.length,hudVisible:savedHudVisible()});api.connectPanel=connect;api.setLiveHudVisible=setHudVisible}}
loadQueue();bind();schedule(180);setInterval(syncState,500);setInterval(checkPanelPresence,1000);window.addEventListener('frutas:event',e=>{sendEvent(e.detail||{});if(e.detail?.event==='background_protection'&&e.detail?.active===false)setTimeout(flushPending,60)});window.addEventListener('frutas:state',e=>{const scope=e.detail?.scope||'game';sendState(scope)});window.addEventListener('pageshow',()=>{loadQueue();setHudVisible(savedHudVisible(),{persist:false});window.LivePlusGameSDK?.installPasteBridge?.($('panelCode'));schedule(180);setTimeout(flushPending,1400)});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){loadQueue();setHudVisible(savedHudVisible(),{persist:false});schedule(350);setTimeout(flushPending,1400)}});
window.FrutasPanelBridge={connect,reconnect,sendState,sendEvent,syncState,getSession:()=>session,getRules:()=>rules.slice(),getTransport:()=>session?.getTransport?.()||'offline',getPanelPresent:()=>panelPresent,getPendingCommands:()=>pendingCommands.map(x=>({...x.data})),flushPending,manifest,setHudVisible,getHudVisible:savedHudVisible};
})();