const { test, expect } = require('@playwright/test');
async function boot(page){const errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.goto('/?qa=1',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.FrutasGame&&window.FrutasLiveActions&&window.FrutasPanelBridge&&window.FrutasActionManager,null,{timeout:15000});return errors}
async function reset(page){await page.evaluate(()=>window.FrutasLiveActions.execute({action:'live_restart',params:{}}));await page.waitForTimeout(250)}
test('smoke: jogo inicia, aceita frutas e fica vivo por 30 segundos',async({page})=>{test.setTimeout(45000);const errors=await boot(page);await reset(page);const started=Date.now();let drops=0;while(Date.now()-started<30000){await page.evaluate(i=>{const g=window.FrutasGame,s=g.getState();if(s.gameOver)g.reset();const m=g.getFieldMetrics();g.dropFruit(i%3,45+((i*47)%Math.max(80,m.width-90)))},drops++);await page.waitForTimeout(360)}const state=await page.evaluate(()=>({state:FrutasGame.getState(),bodies:FrutasGame.getBodies().length}));expect(state.bodies).toBeGreaterThan(0);expect(Number.isFinite(state.state.score)).toBeTruthy();expect(errors).toEqual([])});
test('merge: frutas iguais se juntam e pontuam',async({page})=>{await boot(page);await reset(page);await page.evaluate(()=>{const g=FrutasGame,w=g.getFieldMetrics().width;g.dropFruit(0,w/2)});await page.waitForTimeout(380);await page.evaluate(()=>{const g=FrutasGame,w=g.getFieldMetrics().width;g.dropFruit(0,w/2)});await expect.poll(()=>page.evaluate(()=>FrutasGame.getState().score),{timeout:5000}).toBeGreaterThanOrEqual(2);expect(await page.evaluate(()=>FrutasGame.getBodies().map(b=>b.fruitTier))).toContain(1)});
test('pontuacao: tier final desaparece e soma bonus de 500',async({page})=>{await boot(page);await reset(page);await page.evaluate(()=>{const g=FrutasGame,w=g.getFieldMetrics().width;g.dropFruit(9,w/2)});await page.waitForTimeout(380);await page.evaluate(()=>{const g=FrutasGame,w=g.getFieldMetrics().width;g.dropFruit(9,w/2)});await expect.poll(()=>page.evaluate(()=>FrutasGame.getState().score),{timeout:6000}).toBe(500);expect(await page.evaluate(()=>FrutasGame.getBodies().filter(b=>b.fruitTier===9).length)).toBe(0)});
test('persistencia: mini e gigante sobrevivem ao reload e mini expira corretamente',async({page})=>{test.setTimeout(30000);await boot(page);await reset(page);await page.evaluate(()=>FrutasLiveActions.execute({action:'giant_fruit',params:{tier:2,scale:1.8}}));await page.waitForTimeout(500);await page.evaluate(()=>FrutasLiveActions.execute({action:'mini_fruits',params:{percent:50,duration:4}}));let v=await page.evaluate(()=>{const b=FrutasGame.getBodies()[0];return{scale:b.__liveScale,base:b.__liveBaseScale,mini:FrutasLiveActions.getMiniScale()}});expect(v.base).toBeCloseTo(1.8,1);expect(v.scale).toBeCloseTo(.9,1);await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.FrutasLiveActions&&window.FrutasPanelBridge);v=await page.evaluate(()=>{const b=FrutasGame.getBodies()[0];return{scale:b?.__liveScale,base:b?.__liveBaseScale,mini:FrutasLiveActions.getMiniScale()}});expect(v.base).toBeCloseTo(1.8,1);expect(v.scale).toBeCloseTo(.9,1);await page.waitForTimeout(4500);v=await page.evaluate(()=>{const b=FrutasGame.getBodies()[0];return{scale:b?.__liveScale,base:b?.__liveBaseScale,mini:FrutasLiveActions.getMiniScale()}});expect(v.base).toBeCloseTo(1.8,1);expect(v.scale).toBeCloseTo(1.8,1);expect(v.mini).toBe(1)});
test('reset manual cancela chuva e mini',async({page})=>{await boot(page);await reset(page);await page.evaluate(()=>{FrutasLiveActions.execute({action:'fruit_rain',params:{count:20,maxTier:1}});FrutasLiveActions.execute({action:'mini_fruits',params:{percent:50,duration:30}})});await page.waitForTimeout(700);await page.evaluate(()=>FrutasGame.reset());await page.waitForTimeout(1500);const v=await page.evaluate(()=>({bodies:FrutasGame.getBodies().length,mini:FrutasLiveActions.getMiniScale()}));expect(v.bodies).toBe(0);expect(v.mini).toBe(1)});
test('fim de jogo oferece X e reinicia direto sem abrir configuracoes',async({page})=>{await boot(page);await reset(page);await page.evaluate(()=>{const msg=document.getElementById('gameMessage');msg.hidden=false;msg.innerHTML='FIM DE JOGO<br><small>5.180 pontos</small>';const original=FrutasGame.getState;FrutasGame.getState=()=>({...original(),gameOver:true});FrutasLifecycle.ensureGameOverRestart()});const btn=page.locator('.gameover-restart');await expect(btn).toBeVisible();await expect(btn).toHaveAttribute('aria-label','Reiniciar partida');await btn.click();await expect(page.locator('#gameMessage')).toBeHidden()});
test('manifesto publico tem somente as seis acoes live',async({page})=>{await boot(page);const ids=await page.evaluate(()=>FrutasPanelBridge.manifest().actions.map(a=>a.id));expect(ids).toEqual(['live_restart','remove_points','giant_fruit','fruit_rain','second_chance','mini_fruits'])});
test('remove_points usa economia nova de 100 por padrao',async({page})=>{await boot(page);const def=await page.evaluate(()=>FrutasLiveActions.actions.find(a=>a.id==='remove_points').params[0].default);expect(def).toBe(100)});
test('idempotencia bloqueia comando duplicado',async({page})=>{await boot(page);await reset(page);await page.evaluate(()=>FrutasGame.executeCommand({action:'set_score',params:{amount:500}}));await page.evaluate(async()=>{const cmd={id:'qa-duplicate-1',action:'remove_points',params:{amount:100}};await FrutasLiveActions.execute(cmd);await FrutasLiveActions.execute(cmd)});expect(await page.evaluate(()=>FrutasGame.getState().score)).toBe(400)});
test('acoes live basicas nao quebram a partida',async({page})=>{const errors=await boot(page);await reset(page);await page.evaluate(()=>FrutasLiveActions.execute({action:'fruit_rain',params:{count:5,maxTier:2}}));await page.waitForTimeout(2200);expect(await page.evaluate(()=>FrutasGame.getBodies().length)).toBeGreaterThan(0);await page.evaluate(()=>FrutasLiveActions.execute({action:'second_chance',params:{}}));await page.waitForTimeout(300);expect(await page.evaluate(()=>FrutasGame.getBodies().length)).toBe(0);expect(errors).toEqual([])});
